// ============================================================
// STLエクスポーター（バイナリSTL形式）
// Three.js BufferGeometry → Uint8Array → ダウンロード
// ============================================================

/**
 * BufferGeometry配列をバイナリSTLに変換してダウンロード
 */
export async function exportSTL(geometries: object[], filename: string): Promise<void> {
  const THREE = await import('three')

  // ── ヘルパー：ジオメトリのトライアングル数を正確に取得 ──
  function countTriangles(g: import('three').BufferGeometry): number {
    const index = g.index
    if (index) {
      return Math.floor(index.count / 3)
    } else {
      const pos = g.getAttribute('position')
      if (!pos) return 0
      return Math.floor(pos.count / 3)
    }
  }

  // 全ジオメトリのトライアングル数を集計
  let totalTriangles = 0
  for (const geo of geometries) {
    totalTriangles += countTriangles(geo as import('three').BufferGeometry)
  }

  if (totalTriangles === 0) {
    console.warn('STL export: no triangles found')
    return
  }

  // バイナリSTLバッファ確保
  // ヘッダ(80) + トライアングル数(4) + トライアングルデータ(50 × n)
  const bufferSize = 80 + 4 + 50 * totalTriangles
  const buffer = new ArrayBuffer(bufferSize)
  const view   = new DataView(buffer)

  // ヘッダ（80バイト）
  const header = 'Francis Runner STL - Generated by Water Turbine Selector'
  for (let i = 0; i < 80; i++) {
    view.setUint8(i, i < header.length ? header.charCodeAt(i) : 0)
  }

  // トライアングル総数
  view.setUint32(80, totalTriangles, true)

  let offset = 84
  const vA = new THREE.Vector3()
  const vB = new THREE.Vector3()
  const vC = new THREE.Vector3()
  const cb = new THREE.Vector3()
  const ab = new THREE.Vector3()

  const writeTriangle = (
    ax: number, ay: number, az: number,
    bx: number, by: number, bz: number,
    cx: number, cy: number, cz: number
  ) => {
    // バッファ範囲チェック
    if (offset + 50 > bufferSize) return

    vA.set(ax, ay, az); vB.set(bx, by, bz); vC.set(cx, cy, cz)
    cb.subVectors(vC, vB); ab.subVectors(vA, vB); cb.cross(ab).normalize()

    view.setFloat32(offset, cb.x, true); offset += 4
    view.setFloat32(offset, cb.y, true); offset += 4
    view.setFloat32(offset, cb.z, true); offset += 4
    view.setFloat32(offset, ax, true);   offset += 4
    view.setFloat32(offset, ay, true);   offset += 4
    view.setFloat32(offset, az, true);   offset += 4
    view.setFloat32(offset, bx, true);   offset += 4
    view.setFloat32(offset, by, true);   offset += 4
    view.setFloat32(offset, bz, true);   offset += 4
    view.setFloat32(offset, cx, true);   offset += 4
    view.setFloat32(offset, cy, true);   offset += 4
    view.setFloat32(offset, cz, true);   offset += 4
    view.setUint16(offset, 0, true);     offset += 2
  }

  for (const geo of geometries) {
    const g = geo as import('three').BufferGeometry
    const posAttr = g.getAttribute('position') as import('three').BufferAttribute
    if (!posAttr) continue
    const index = g.index

    if (index) {
      const count = Math.floor(index.count / 3) * 3
      for (let i = 0; i < count; i += 3) {
        const a = index.getX(i), b = index.getX(i + 1), c = index.getX(i + 2)
        writeTriangle(
          posAttr.getX(a), posAttr.getY(a), posAttr.getZ(a),
          posAttr.getX(b), posAttr.getY(b), posAttr.getZ(b),
          posAttr.getX(c), posAttr.getY(c), posAttr.getZ(c),
        )
      }
    } else {
      const count = Math.floor(posAttr.count / 3) * 3
      for (let i = 0; i < count; i += 3) {
        writeTriangle(
          posAttr.getX(i),   posAttr.getY(i),   posAttr.getZ(i),
          posAttr.getX(i+1), posAttr.getY(i+1), posAttr.getZ(i+1),
          posAttr.getX(i+2), posAttr.getY(i+2), posAttr.getZ(i+2),
        )
      }
    }
  }

  // ダウンロード
  const blob = new Blob([buffer], { type: 'application/octet-stream' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
